=== ZhidkovAleksandr/HW2_Web/src/Task4/sources/s2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="factory" type="factoryType"/>
  <xs:complexType name="factoryType">
    <xs:sequence>
      <xs:element type="candyType" name="candy" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="candyType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
         <xs:element name="taste" type="xs:string"/>
         <xs:element name="color" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== ZhidkovAleksandr/HW2_Web/src/Task4/sources/candies.xml
<?xml version="1.0" encoding="UTF-8" ?>
<factory xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation = "s2.xsd">
  <candy>
    <name>snickers</name>
    <taste>peanut</taste>
    <color>brown</color>
  </candy>
   <candy>
    <name>bounty</name>
    <taste>coconut</taste>
    <color>black</color>
   </candy>
    <candy>
    <name>twix</name>
    <taste>caramel</taste>
    <color>brown</color>
  </candy>
</factory>
